line-length = 132
#target-version = "py313"
select = ["E4", "E7", "E9", "F", "Q"]

[flake8-quotes]
inline-quotes = "single"
multiline-quotes = "single"
docstring-quotes = "double"
avoid-escape = false

[lint]
select = ["E4", "E7", "E9", "F", "Q", "F", "E", "W", "I", "UP", "C4", "A", "TID"]
ignore = []

[format]
quote-style = "single"
