line-length = 132
#target-version = "py311"
select = ["E4", "E7", "E9", "F", "Q"]

[flake8-quotes]
inline-quotes = "single"
multiline-quotes = "single"
docstring-quotes = "double"
avoid-escape = false

[lint]
select = ["E4", "E7", "E9", "F", "Q"]
ignore = []

[format]
quote-style = "single"
